version: '3'
services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass

    worker:
        build:
            context: ./
            dockerfile: celery-docker-file
        environment:
          - USER=admin
          - PASS=mypass
          - HOSTNAME=rabbit
          - PORT=5672
        volumes:
            - ./src:/app/
        links:
            - rabbit
        depends_on:
            - rabbit
        restart: on-failure

    webservice:
        build:
            context: ./
            dockerfile: app-docker-file
        environment:
            - USER=admin
            - PASS=mypass
            - HOSTNAME=rabbit
            - PORT=5672
        ports:
          - 4555:4555
        volumes:
            - ./src:/app/
        links:
            - rabbit
        depends_on:
            - rabbit